Quarkus Buildpack
paketo-buildpacks/rfcs pull request #171
Opened 2022-04-06 11:56 UTC by matejvasek

Signed-off-by: Matej Vasek <mvasek@redhat.com>

## Summary

## Use Cases

## Checklist

* [ ] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [ ] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

2022-04-06 11:59 UTC, matejvasek commented
/cc @dmikusa-pivotal

2022-04-06 11:59 UTC, matejvasek commented
/cc @BarDweller

2022-04-06 12:09 UTC, matejvasek commented
/cc @cmoulliard

2022-04-06 14:59 UTC, dmikusa-pivotal reviewed
Some initial comments.

2022-04-06 14:59 UTC, dmikusa-pivotal commented on text/java/0012-quarkus.md
> +The buildpack would just set environment variables for the `maven`and `native-image` buildpacks.
```suggestion
The primary purpose of this buildpack is to environment variables for the `paketo-buildpacks/maven` and `paketo-buildpacks/native-image` buildpacks. Building a Quarkus application is presently possible but requires setting multiple environment variables to properly configure the buildpacks. This proposed buildpack will enable users to build Quarkus applications without additional configuration.
```

2022-04-06 14:59 UTC, dmikusa-pivotal commented on text/java/0012-quarkus.md
> +* The Buildpack will be added to the `java` and `java-native-image` buildpacks groups just before the `maven` buildpack.
```suggestion
* The Buildpack will be added to the `paketo-buildpacks/java` and `paketo-buildpacks/java-native-image` buildpacks groups just before the `paketo-buildpacks/maven` buildpack.
```

2022-04-06 14:59 UTC, dmikusa-pivotal commented on text/java/0012-quarkus.md
> +However, it would be much more complicate to implement, and it would lead to duplicity.
I'd be curious to get your thoughts on a few things here:

1. How important do you see these two items? a.) being able to build different package types and b.) better control over layering. They seem at least moderately important, IMHO.

2. What are the challenges with implementing them with the proposed architecture here? For example, we do layer slicing in the Spring Boot buildpack but it's not controlling the build phase. That just happens after the build.
    
    If there is missing functionality, it could also be possible to extend existing buildpacks to add support for ways for a separate Quarkus buildpack to influence these aspects in the existing buildpacks.

3. Does Quarkus always use Maven for builds? or does it use Gradle too? I'm just trying to understand the amount of functionality that would need to be combined into one buildpack to make all this work in a more monolithic buildpack? It would obviously be less desirable to have a monolithic buildpack, but we do have some of this functionality broken into libraries already, like libbs, and we can technically import code from other buildpacks so you could possibly import existing aspects from a buildpack to combine them without as much code duplication. Anyway, I don't want to 100% rule this out. We should weigh the benefits versus the implementation.

2022-04-06 15:10 UTC, matejvasek commented on text/java/0012-quarkus.md
> +However, it would be much more complicate to implement, and it would lead to duplicity.
>Does Quarkus always use Maven for builds? or does it use Gradle too?

It can also use `gradle` so support for is should be added in near future.

2022-04-06 15:11 UTC, matejvasek commented on text/java/0012-quarkus.md
> +However, it would be much more complicate to implement, and it would lead to duplicity.
>we do layer slicing in the Spring Boot buildpack but it's not controlling the build phase

I think that springboot expose some config files describing layering to be used. AFAIK Quarkus is not producing such a file.

2022-04-06 15:20 UTC, matejvasek commented on text/java/0012-quarkus.md
> +However, it would be much more complicate to implement, and it would lead to duplicity.
>being able to build different package types 

In order to set envvars for the `maven` buildpack the quarkus buildpack has to run before it. But to detect what build type was used is has to run after it. I would have to have multiple Quarkus buildpacks to handle this: `quarkus-pre-maven` `quarkus-post-maven`.

2022-04-06 15:23 UTC, matejvasek commented on text/java/0012-quarkus.md
> +However, it would be much more complicate to implement, and it would lead to duplicity.
When spring boot creates layers, does it remove `/workspace/`?

2022-04-06 15:25 UTC, matejvasek commented on text/java/0012-quarkus.md
> +However, it would be much more complicate to implement, and it would lead to duplicity.
>How does Quarkus normally define its layers? Is that done through the Dockerfiles it uses or some other means?

Scaffold-ed Quarkus project usually contains Dockerfiles with `COPY` in efficient order.

2022-04-06 15:31 UTC, matejvasek commented on text/java/0012-quarkus.md
> +However, it would be much more complicate to implement, and it would lead to duplicity.
One of the things that bothers me is: the `maven` buildpacks does two things:
* builds the app
* copies artifacts somewhere

In order to copy appropriate artifacts I have to set envvars for the `maven` buildpack therefore I have to run before it.
But in order to detect what build type out of the three (legacy-jar, fast-jar, uber-jar) I have to run after the `maven` buildpack. This make me to enforce only one of the package types.

2022-04-06 15:55 UTC, BarDweller commented on text/java/0012-quarkus.md
> +However, it would be much more complicate to implement, and it would lead to duplicity.
The maven buildpack _also_ downloads maven.. it's really doing quite a lot.. I'd love to see the maven buildpack split off the provisioning of maven, so then I can provide it, and it can use it. (Admittedly there are some issues here related to maven versions, and supported flags etc). 

I guess if a separate buildpack provisioned maven, you could use the provisioned maven to query the project to ask which deployment type was configured, and then set the appropriate env vars ? then the build-with-maven buildpack could do the actual build with that knowledge already in place. 

(I have a related problem, but it's not so easily solved.. needing to determine which level of java is being asked for by the maven project.. I can hack an approximation by grepping the pom.xml, but if the version is configured in a parent pom that's being read from a maven repo, then it gets harder, and the easiest way is to invoke `mvn` to ask the project for the value of the resolved property.. I'm playing with trying to do this from a natively compiled java app, to avoid the jvm dependency when figuring out which jvm you need).

2022-04-06 15:57 UTC, BarDweller commented on text/java/0012-quarkus.md
> +However, it would be much more complicate to implement, and it would lead to duplicity.
> How does Quarkus normally define its layers? Is that done through the Dockerfiles it uses or some other means?

I can make this a circular problem ;p one way quarkus can build a container, is by using buildpacks ;p (it also supports various other container-image extensions that each try to do the right thing for layers.. https://quarkus.io/guides/container-image ).. as well as Dockerfiles etc.

2022-04-06 15:58 UTC, matejvasek commented
/cc @maxandersen

2022-04-06 17:10 UTC, matejvasek commented on text/java/0012-quarkus.md
> +However, it would be much more complicate to implement, and it would lead to duplicity.
@maxandersen I think it won't be necessary I should be able to determine layering based on build type (uber/legacy/fast).

2022-04-06 18:41 UTC, dmikusa-pivotal commented on text/java/0012-quarkus.md
> +However, it would be much more complicate to implement, and it would lead to duplicity.
>The maven buildpack also downloads maven.. it's really doing quite a lot.. I'd love to see the maven buildpack split off the provisioning of maven, so then I can provide it, and it can use it. (Admittedly there are some issues here related to maven versions, and supported flags etc).

@BarDweller we provide support for maven wrapper which is the suggested way of controlling the specific Maven version that gets used. Or are you saying you want the opposite? Or the buildpack to provide Maven using it's current mechanisms but not do any build?

2022-04-06 18:44 UTC, dmikusa-pivotal commented on text/java/0012-quarkus.md
> +However, it would be much more complicate to implement, and it would lead to duplicity.
>(I have a related problem, but it's not so easily solved.. needing to determine which level of java is being asked for by the maven project.. I can hack an approximation by grepping the pom.xml, but if the version is configured in a parent pom that's being read from a maven repo, then it gets harder, and the easiest way is to invoke mvn to ask the project for the value of the resolved property.. I'm playing with trying to do this from a natively compiled java app, to avoid the jvm dependency when figuring out which jvm you need).

That's interesting. We could talk about trying to support something like this. There's a thread on Paketo Slack. That would probably be a better place as it'll probably be a more lengthy conversation. Are you on the Paketo Slack?

2022-04-06 18:50 UTC, dmikusa-pivotal commented on text/java/0012-quarkus.md
> +However, it would be much more complicate to implement, and it would lead to duplicity.
>I think it won't be necessary I should be able to determine layering based on build type (uber/legacy/fast).

Ok, so this circles back to the conversation on Slack about possibly splitting up the build tools buildpacks. It'll be a big project though and something that should have it's own RFC. Bringing things back to this RFC, should we proceed here? or hold this off until we make sufficient changes to the build tools buildpacks?

It'd be nice to get a Quarkus buildpack that's working, but I don't want to release something that we can't migrate into the state required to support slicing and all of the package types if it'll break users.

2022-04-06 20:18 UTC, matejvasek commented on text/java/0012-quarkus.md
> +However, it would be much more complicate to implement, and it would lead to duplicity.
What is `build tools buildpack` ?

2022-04-06 20:51 UTC, dmikusa-pivotal commented on text/java/0012-quarkus.md
> +However, it would be much more complicate to implement, and it would lead to duplicity.
>What is build tools buildpack ?

Sorry, I sometimes use that to refer to the full set of all the build tools related buildpacks we support (Gradle, Maven, SBT, etc...). Usually conversations focus on Maven & Gradle, but there are others we have to consider in changes like this too.

2022-04-07 13:10 UTC, matejvasek commented
/cc @n1hility

2022-05-10 19:45 UTC, matejvasek commented
Actually it seems slicing is not an issue. I can forward declare slices even thought the directories/files are yet to be created by some other buildpack.

So the only inconvenience is that the buildpack has to force some specific packaging type (e.g. `fast-jar`) which renders value defined in `application.properties` or in the `QUARKUS_PACKAGE_TYPE` envvar unused.
I think we could live with that.

2022-05-10 19:55 UTC, matejvasek commented
>So the only inconvenience is that the buildpack has to force some specific packaging type (e.g. fast-jar) which renders value defined in application.properties or in the QUARKUS_PACKAGE_TYPE envvar unused.
I think we could live with that.

I don't know, maybe the `quarkus.package.type` property could be somehow evaluated even without running `mvn` build.

2022-05-16 14:11 UTC, matejvasek commented
@maxandersen  The content of `target/quarkus-app/quarkus:
```
generated-bytecode.jar
quarkus-application.dat
transformed-bytecode.jar
```
seems to be different on each build.
Is there a way to make these reproducible?

2022-05-18 14:27 UTC, maxandersen commented
> @maxandersen is there any possible issue with forcing `fast-jar` and disregarding package type declared in `application.properties`?

Probably not - except build and deploy features of quarkus will listen to the property - but if buildpack does the container building and therefore have to force a behavior I don't think it will be a problem.

2022-05-25 11:00 UTC, matejvasek commented on text/java/0012-quarkus.md
> +However, it would be much more complicate to implement, and it would lead to duplicity.
It turned out I can setup layering even with current solution.
The package type is not too important.

2022-06-16 14:59 UTC, dmikusa-pivotal requested changes
I think this looks good, just a few minor things to clean up. If these look Ok to you, just merge them and I'll approve. 

I took a look at your buildpack too and that looks good. Thanks for putting this together.

2022-06-16 14:59 UTC, dmikusa-pivotal commented on text/java/0012-quarkus.md
> +Provide a Quarkus Buildpack which will be part of the order groups for `paketo-buildpacks/java` and `paketo-buildpacks/java-native-image`.
```suggestion
Provide a Quarkus Buildpack which will be part of the order groups for `paketo-buildpacks/java`, `paketo-buildpacks/java-azure`, and `paketo-buildpacks/java-native-image`.
```

2022-06-16 14:59 UTC, dmikusa-pivotal commented on text/java/0012-quarkus.md
> +The Quarkus Buildpack will be moved into the paketo-buildpacks Github organization and added to the Java sub-team. Maintenance for this buildpack will be provided by the Java subteam.
```suggestion
The [Quarkus Buildpack][b] will be moved into the paketo-buildpacks Github organization and added to the Java sub-team. Maintenance for this buildpack will be provided by the Java subteam.
```

2022-06-16 14:59 UTC, dmikusa-pivotal commented on text/java/0012-quarkus.md
> +* The Buildpack will be published to gcr.io/paketo-buildpacks/quarkus
```suggestion
* The Buildpack will be published to `gcr.io/paketo-buildpacks/quarkus`
```

2022-06-16 14:59 UTC, dmikusa-pivotal commented on text/java/0012-quarkus.md
> +* The Buildpack will be added to the `paketo-buildpacks/java` and `paketo-buildpacks/java-native-image` buildpacks groups just before the `paketo-buildpacks/maven` buildpack.
```suggestion
* The Buildpack will be added to the `paketo-buildpacks/java`, `paketo-buildpacks/java-azure`, and `paketo-buildpacks/java-native-image` buildpacks groups just before the `paketo-buildpacks/maven` buildpack.
```

2022-06-16 14:59 UTC, dmikusa-pivotal commented on text/java/0012-quarkus.md
> +* ~~Better control over layering: separating directories according probability of their modification (application code vs. library code).~~
You have some parts ~~struck out~~, if these are no longer items of concern, I would suggest we just remove them.

2022-06-16 14:59 UTC, dmikusa-pivotal commented on text/java/0012-quarkus.md
> +However, it would be much more complicate to implement, and it would lead to duplicity.
```suggestion
However, it would be much more complicated to implement, and it would lead to duplicity.
```

2022-06-16 14:59 UTC, dmikusa-pivotal commented on text/java/0012-quarkus.md
> +
I would like to see what the proposed order group is for `paketo-buildpacks/java` (the others should be basically the same).

2022-06-16 14:59 UTC, dmikusa-pivotal commented on text/java/0012-quarkus.md
> +This buildpack will be adopted by the Java Buildpacks team and transferred to the `paketo` GitHub organization.
```suggestion
This buildpack will be adopted by the Java Buildpacks team and transferred to the `paketo` GitHub organization as described in the [Detailed Explanation](#detailed-explanation) section above.
```

2022-06-21 16:25 UTC, ekcasey commented on text/java/0012-quarkus.md
> +## Detailed Explanation
I think it would be good to include a description of the detection criteria here.

After reading the docs from the POC I would like to discuss:
1. could/should we also handle the case where a quarkus fast-jar is provided to the build, rather than building from source?
2. bikeshedding around what to do if some of the env vars are set by the user. If they are set to desired values already maybe this buildpack should still detect?

2022-06-21 18:36 UTC, matejvasek commented on text/java/0012-quarkus.md
> +## Detailed Explanation
>a mechanism to disable the buildpack (an escape hatch in the case of false detection)

maybe we could add some envvar e.g. `QUARKU_BP_DISABLED` ?

2022-06-21 18:42 UTC, matejvasek commented on text/java/0012-quarkus.md
> +## Detailed Explanation
>could/should we also handle the case where a quarkus fast-jar is provided to the build, rather than building from source?

not sure what you mean

2022-06-21 18:43 UTC, matejvasek commented on text/java/0012-quarkus.md
> +  --env "BP_MAVEN_BUILT_ARTIFACT=target/native-sources/*" \
So far this BP handles maven only. Definitely would be good to support gradle too. It could be first feature.

2022-06-21 18:43 UTC, matejvasek commented on text/java/0012-quarkus.md
> +## Detailed Explanation
> > a mechanism to disable the buildpack (an escape hatch in the case of false detection)
> 
> maybe we could add some envvar e.g. `QUARKU_BP_DISABLED` ?

How do other BPs handle this?

2022-06-28 16:09 UTC, ekcasey commented on text/java/0012-quarkus.md
> +However, it would be much more complicated to implement, and it would lead to duplicity.
```suggestion
However, it would be much more complicated to implement, and it would lead to duplication.
```

2022-06-28 16:33 UTC, ekcasey commented on text/java/0012-quarkus.md
> +## Detailed Explanation
> what do you mean by:
> > could/should we also handle the case where a quarkus fast-jar is provided to the build, rather than building from source?

Sorry I could have been more clear here. I'll elaborate.

Right now with a spring native app it is possible to build the JAR locally with maven and then build the image from the JAR using buildpacks:
```
./mvnw -Dmaven.test.skip=true package
pack build samples/native --builder paketobuildpacks/builder:tiny -p ./target/demo-0.0.1-SNAPSHOT.jar --env BP_NATIVE_IMAGE=true
```

Do we want to support a workflow like this for quarkus? Maybe it's impossible because you lose the `native-image.args` file but if this is a workflow users would want we could look into options such as having the buildpack set the native image build arguments directly.

2022-06-28 17:09 UTC, ekcasey commented on text/java/0012-quarkus.md
> +## Detailed Explanation
> That's how it is implemented already: https://github.com/matejvasek/quarkus-bp/blob/main/quarkus/detect.go#L27
Edit: sry it's actually other way around; I think we shouldn't "fight" users who wants to set envvar by themselves.

I guess I am just generally asking for these details to be included in this RFC document for future reference and so we can discuss the pros/cons of various changes before we accept the buildpack and include it in the composite.

2022-06-28 18:08 UTC, matejvasek commented on text/java/0012-quarkus.md
> +## Detailed Explanation
@ekcasey  I can see it working like:

```
./mvnw -Dmaven.test.skip=true -Dquarkus.package.type=native-source package
pack build samples/native --builder paketobuildpacks/builder:tiny -p ./target/native-sources --env BP_NATIVE_IMAGE=true --env BP_NATIVE_IMAGE_BUILD_ARGUMENTS="$(cat ./target/native-sources/native-image.args)"
```
But it doesn't work now because `-p` has to be jar not a directory containing jars.

2022-07-12 17:06 UTC, ekcasey commented on text/java/0012-quarkus.md
> +## Detailed Explanation
I think this buildpack is a good idea but, If you don't mind @matejvasek , I would like to see the answers to some of these questions included in the RFC not just answers in the comments.

I think it's better to include the following in the RFC itself, not just in the linked repo
1. the detection criteria
2. the behavior at build time
3. supported configurations
4. opportunities for future extensions

This will give us a permanent record of the plan and intentions at the time of approval (things may change later), and give anyone reviewing RFC an opportunity to request on any of the above details if they would like to.

2022-07-13 12:13 UTC, matejvasek commented on text/java/0012-quarkus.md
> +## Detailed Explanation
OK, I'll update the RFC.

2022-07-13 13:44 UTC, matejvasek commented
@ekcasey @dmikusa-pivotal I updated the PR.

2022-07-15 15:18 UTC, ekcasey approved these changes

2022-07-18 18:21 UTC, dmikusa-pivotal approved these changes

2022-07-26 18:05 UTC, joshuatcasey commented
2022-07-26: ready to merge by @dmikusa-pivotal

2022-07-28 15:07 UTC, merged