RFC: Add licenses to dependency server
paketo-buildpacks/rfcs pull request #72
Opened 2021-06-07 19:58 UTC by sophiewigmore

## Summary

[Readable](https://github.com/sophiewigmore/rfcs/blob/sophie/dependency-licenses/text/0028-dependency-server-licenses.md)

## Use Cases

Resolves https://github.com/paketo-buildpacks/rfcs/issues/19

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [X] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

2021-06-14 17:02 UTC, ryanmoran requested changes

2021-06-14 17:02 UTC, ryanmoran commented on text/0028-dependency-server-licenses.md
> +because information about the licesnse(s) of a dependency is a valuable and
```suggestion
because information about the license(s) of a dependency is a valuable and
```

2021-06-14 17:02 UTC, ryanmoran commented on text/0028-dependency-server-licenses.md
> +thier apps use license that comply with thier use cases.
```suggestion
their apps use license that comply with their use cases.
```

2021-06-14 17:02 UTC, ryanmoran commented on text/0028-dependency-server-licenses.md
> +* `licenses`: an array of licenses that are used by the dependency
Can you make sure to include a specification of what the acceptable values for this field are?

2021-06-15 15:34 UTC, ryanmoran commented
I'd argue that this doesn't need to be a top-level RFC and could instead go into the [`text/dependencies`](https://github.com/paketo-buildpacks/rfcs/tree/main/text/dependencies) directory and get approved by the Dependencies Maintainers subteam.

2021-06-15 16:51 UTC, ekcasey approved these changes

2021-06-16 22:51 UTC, brayanhenao approved these changes

2021-06-17 15:37 UTC, ryanmoran approved these changes

2021-06-21 17:45 UTC, merged